name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import sanity
        run: |
          python - <<'PY'
          import importlib
          for m in ["src.mixup","src.metrics","src.utils.seed","src.utils.io","src.data","src.models","src.train"]:
              importlib.import_module(m)
          print("Imports OK")
          PY
